version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  matrix:
    - configuration: Debug
      platform: Any CPU
    - configuration: DesktopRelease
      platform: Any CPU
    - configuration: AndroidRelease
      platform: ARM
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - ps: $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
  - ps: (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
  - ps: 7z x $zipPath | Out-Null
  - ps: Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"
before_build:
  - ps: dotnet restore
  - nuget restore ".\MonoAGS.sln"
  - xamarin-component.exe restore ".\MonoAGS.sln"
build:
  project: .\MonoAGS.sln
  verbosity: minimal
test_script:
- ps: >-
    if($env:CONFIGURATION -eq "Debug")
    {
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe "-targetargs:""Source\Tests\bin\Debug\Tests.dll"" /noshadow" -filter:"+[AGS.Engine]*" -output:opencoverCoverage.xml
    
    .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i ./opencoverCoverage.xml --repoToken 7hZHP5bLxlE8doYiQg6b79oF7wM6jlecs
    }
