version: 1.0.{build}
skip_tags: true
os: Visual Studio 2017
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  JavaSdkDirectory: C:\Program Files (x86)\Java\jdk1.8.0
  git_token:
    secure: LGUAs6fAe/4AL1s3r3jYG3CN5GOgOq+OW+ngaoa+u9HXPhH/jeqarcOV/qQwSohM
  github_email:
    secure: gRFz90kCueB13wW3WV/Jve7i2hzFfnwdOz2HRGwOyD4=
  matrix:
    - configuration: DOCS
      platform: x86 #this configuration is for the docs only, we apparently can't use "Any CPU" because of a bug: https://github.com/dotnet/docfx/issues/1078
    - configuration: Debug
      platform: Any CPU
    - configuration: DesktopRelease
      platform: Any CPU
    - configuration: AndroidRelease
      platform: ARM
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
  - ps: $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
  - ps: (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
  - ps: 7z x $zipPath | Out-Null
  - ps: Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"
  - npm install gh-pages -g
before_build:
  - ps: dotnet restore
  - nuget restore ".\MonoAGS.sln"
  - xamarin-component.exe restore ".\MonoAGS.sln"
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $env:CONFIGURATION -eq "DOCS")
        {
            cinst docfx -y
        }
build:
  project: .\MonoAGS.sln
  verbosity: minimal
test_script:
- ps: |
    if($env:CONFIGURATION -eq "Debug")
    {
        .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe "-targetargs:""Source\Tests\bin\Debug\Tests.dll"" /noshadow" -filter:"+[AGS.Engine]*" -output:opencoverCoverage.xml

        .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i ./opencoverCoverage.xml --repoToken 7hZHP5bLxlE8doYiQg6b79oF7wM6jlecs
    }
    elseif ($env:CONFIGURATION -eq "DesktopRelease")
    {
        .\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe .\Source\Tests\bin\Release\Tests.dll
        
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    }
after_build:
# Several examples of how to build the docs:
# https://github.com/docascode/docfx-seed/blob/master/appveyor.yml
# https://github.com/richardschneider/net-ipfs-core/blob/master/appveyor.yml
# https://github.com/cameron-elliott/LimeVideoSDK/blob/master/appveyor.yml
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -And $env:CONFIGURATION -eq "DOCS")
        {
            docfx Docs/docfx.json
            if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
            git config --global core.autocrlf input
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_token):x-oauth-basic@github.com`n"
            git config --global user.email %github_email%
            git config --global user.name "tzachshabtay"
            gh-pages -d Docs\_site -m "CI Docs Updates"
        }
